postgresql:
  restart: always
  image: m0elnx/postgresql-32bit:latest
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql
gitlab:
  restart: always
  image: m0elnx/gitlab-32bit:latest
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - DEBUG=false
    - TZ=Asia/Kolkata
    - GITLAB_TIMEZONE=Kolkata

    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string

    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_RELATIVE_URL_ROOT=

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=notifications@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00

    - GITLAB_DOWNLOADS_DIR=/home/git/data/tmp/downloads
    - GITLAB_LFS_ENABLED=true
    - GITLAB_LFS_OBJECTS_DIR=/home/git/data/shared/lfs-objects
    - GITLAB_SHARED_DIR=/home/git/data/shared
    - GITLAB_ARTIFACTS_ENABLED=true
    - GITLAB_ARTIFACTS_DIR=/home/git/data/shared/artifacts

    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false

    - OAUTH_BLOCK_AUTO_CREATER_USERS=false
    - OAUTH_AUTO_SIGNIN_WITH_PROVIDER=github,bitbucket,google_oauth2
    - OAUTH_BITBUCKET_APP_SECRET=bitbucket-app-secret-here
    - OAUTH_BITBUCKET_API_KEY=bitbucket-api-key-here
    - OAUTH_ALLOW_SSO=true
    - OAUTH_GITHUB_API_KEY=github-api-key-here
    - OAUTH_GITHUB_APP_SECRET=github-app-secret-here
    - OAUTH_GOOGLE_API_KEY=really-long-alphanumeric-google-generated-key-goes-here
    - OAUTH_GOOGLE_APP_SECRET=random-generated-google-app-secrete-goes-here

  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
redis:
  restart: always
  image: m0elnx/redis-32bit:latest
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis
